name: agrich_app_v2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  go_router: ^16.2.1
  flutter_riverpod: ^2.4.9
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_database: ^12.0.1
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  video_player: ^2.8.1
  chewie: ^1.7.4
  intl: ^0.20.2
  uuid: ^4.2.1
  path: ^1.8.3
  equatable: ^2.0.5
  intl_phone_field: ^3.2.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  pinput: ^5.0.2
  flutter_chat_ui: ^2.9.0
  weather: ^3.1.1
  timeago: ^3.7.1
  flutter_launcher_icons: ^0.14.4
  share_plus: ^11.1.0
  mask_text_input_formatter: ^2.9.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icons/ic_launcher_monochrome.png"