// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4ZQj_GcAwnmZGZ_8Q9bGskvUM4pE44Q',
    appId: '1:89578726597:ios:db08647eb4b631ecfdfcac',
    messagingSenderId: '89578726597',
    projectId: 'agrich-app-v2',
    databaseURL: 'https://agrich-app-v2-default-rtdb.firebaseio.com',
    storageBucket: 'agrich-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.agrichAppV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhstJTwQ1zeprxcp84vJJOkyatAF55yFI',
    appId: '1:89578726597:android:9ff47f8089730df2fdfcac',
    messagingSenderId: '89578726597',
    projectId: 'agrich-app-v2',
    databaseURL: 'https://agrich-app-v2-default-rtdb.firebaseio.com',
    storageBucket: 'agrich-app-v2.firebasestorage.app',
  );

}